### ISSUE TITLE
Récupération des information d'un membre / porteur d'une idée

### ISSUE THREAD

**Issue by rjansem** [SopraSteriaGroup/initiatives_backend_auth#11]
Informations seront retournées dans le WS de détail d'une soprIdée

**Comment by cegiraud** [comment]
@All
Je pense que les utilisateurs doivent être gérés par les MS d'auth (par rapport à la gestion des roles). Qu'en pensez vous?
Je pense qu'il faut ajouter dessus le WS qui va bien?

**Comment by cegiraud** [comment]
et si oui je le rajoute et je m'affecte cette issue. Comme ça ce MS (service-auth) sera bouclé.

**Comment by jntakpe** [comment]
Je sais pas @rjansem avait créé un user-service pour gérer les users je crois

**Comment by cegiraud** [comment]
Ouais mais du coup ca pose un pb d'authentification.
Je peux pas appeler un autre MS tant que je n'ai pas de token.

**Comment by cegiraud** [comment]
Il est tout vide son MS de toutes façons :)

**Comment by rjansem** [comment]
Yes en fait je comptais y mettre les services de première authentification dont j'ai mis une partie dans sopridee service. Et tout ce qui a attrait aux users en tant que membre ou porteur d'une idée

**Comment by cegiraud** [comment]
Le truc c'est qu'il me faut forcément une manière de connaître les rôles d'un user au moment où je fais mon token. Et tant que j'ai pas de token j'appelle pas un autre MS. Donc il faut un peu du user chez moi. Du coup je pensais exposer les méthodes de détails.

**Comment by cegiraud** [comment]
Option 2: 
Côté auth-service on ne gère juste que l'association entre username et rôles. Et on expose les méthodes qui vont bien. Le reste sera géré dans un MS sopridee.

**Comment by cegiraud** [comment]
L'option 2 est plus orientée MS non ? 
Chaque MS ne doit gérer que ce que pour quoi il est fait. Vous en pensez quoi ?

**Comment by rjansem** [comment]
Pour moi auth service gere lauth, les rôles, voire la première connexion et l'envoi du code d'activation
Le user service géré l'utilisateur en tant que participant ou porteur d'une idée.

**Comment by cegiraud** [comment]
Merci de tes réponses :). 

La gestion de la première connexion et mail je pense que ça serait mieux dans l'autre en effet.

**Comment by cegiraud** [comment]
on a bien un WS qui recherche les détails d'un user
