### ISSUE TITLE
Quelle base de données ?

### ISSUE THREAD

**Issue by jntakpe** [SopraSteriaGroup/initiatives_backend_auth#17]
Il nous faut choisir une base de données pour le projet. A savoir que chaque microservice peut avoir une techno de DB différente.
On fait les propositions en commentaire.

**Comment by jntakpe** [comment]
Par défaut, je propose **MongoDB**. Si du cache est nécessaire alors on ajoute **Redis** en plus

**Comment by Jmadih** [comment]
Je pensais qu'on aurait besoin d'une base relationnel sur ce projet ?

**Comment by rjansem** [comment]
Pourquoi mongoDB ? Quel avantage par rapport à du relationnel pour notre besoin ? Les perfs ? Rapidité de mise en place ?

**Comment by jntakpe** [comment]
Parce que j'ai pas envie de me faire chier à gérer un schéma et parce que c'est plus simple à mettre en oeuvre en local et surtout sur le cloud.
Les perfs sincèrement je ne pense pas que ce soit important dans notre cas.
Ensuite comme écrit plus haut on peut avoir des technos différentes par service par exemple je ne vois pas d’intérêt à gérer auth-service en NoSQL donc dans ce cas ma préco serait **H2** en local pour les autres envs **PostgreSQL**

**Comment by jntakpe** [comment]
Bon ça sera MongoDB
